version: '3'
services:
  app:
    container_name: serve-ready-chatbot
    image: serve-ready-chatbot:aih
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
    restart: always
