version: '3'
services:
  app:
    container_name: serve-ready-chatbot
    image: serve-ready-chatbot:aih
    build: .
    ports:
      - "80:80"
    environment:
      - OPENAI_API_KEY: ${OPENAI_API_KEY} 
      - TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      - LANGCHAIN_API_KEY: ${LANGCHAIN_API_KEY}
      
